import { ArrowUpRight, Check, Megaphone, PenTool, UsersRound } from 'lucide-react'
import SvgMotionScene from './SvgMotionScene'
import './JoinUs.css'

const roles = [
  { number: '01', title: 'General volunteer', icon: UsersRound, description: 'Help shape the future of accessible education through content creation, social media, outreach, or research. No previous experience is required—only care for the work.', benefits: ['Flexible remote hours', 'Certificate of contribution', 'Work at your own pace'], links: [{ label: 'Apply to volunteer', link: 'https://docs.google.com/forms/d/e/1FAIpQLSd0wjV73RN4RSCrDU7RhLd31gw8ZBoHiQbI1q9L0dhKdeOCjg/viewform?usp=header' }] },
  { number: '02', title: 'Chapter founder', icon: Megaphone, description: 'Build a local or school-based team to create and share learning materials, connect with your community, and carry Flamivor’s work forward.', benefits: ['Founder’s certificate', 'Direct support from the core team', 'Official chapter Instagram'], links: [{ label: 'Start a chapter', link: 'https://docs.google.com/forms/d/e/1FAIpQLSeI2Aw8Bd6rMCMt6VJL02WpN9aY6w0g9n7pdupkuyCgy_gJ_g/viewform?usp=dialog' }] },
  { number: '03', title: 'Executive team', icon: UsersRound, description: 'Help lead the organisation through strategy, department management, creative direction, and volunteer coordination.', benefits: ['Leadership experience', 'Executive title & certificate', 'Portfolio and collaboration'], links: [{ label: 'Apply to the executive team', link: 'https://docs.google.com/forms/d/e/1FAIpQLSei33hS90nZBKNibIjMA456mYkTLNGVYcI4THY4NxnLo1HWPg/viewform?usp=header' }] },
  { number: '04', title: 'Social media internship', icon: PenTool, description: 'Create short-form video or original educational graphics that make Flamivor’s work easier to discover, understand, and share.', benefits: ['Remote creative work', 'Portfolio-worthy projects', 'Certificate of completion'], links: [{ label: 'Apply for Reels', link: 'https://docs.google.com/forms/d/e/1FAIpQLScqgxV-gJGhL2HBcbi0NF9ipnThZPnZ2iq1rhQZj_bskiNybA/viewform?usp=dialog' }, { label: 'Apply for graphics', link: 'https://docs.google.com/forms/d/e/1FAIpQLScOSZq50rdFlC1N8h7FOLCKNwQ1TK8iL7XVTTxv2NnZLnl1Vg/viewform?usp=header' }] },
]

export default function JoinUs() {
  return <main className="join-page">
    <section className="join-hero" aria-labelledby="join-heading"><SvgMotionScene scene="join" className="join-svg-scene" /><div className="join-hero-copy"><p className="join-eyebrow">Join the work</p><h1>Bring your <em>spark</em><br />to the circle.</h1><p>Flamivor grows when young people turn what they care about into something useful for someone else.</p></div><figure className="join-hero-image"><img src="https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=84" alt="Students collaborating together" fetchPriority="high" /><figcaption>Student-led from the start</figcaption></figure></section>
    <section className="join-intro" aria-labelledby="join-intro-heading"><p className="join-eyebrow">There is no single way to contribute</p><h2 id="join-intro-heading">Choose the kind of<br />difference you want to make.</h2><p>Whether you want to help one project, lead a chapter, build a portfolio, or guide a whole team, there is a place to begin.</p></section>
    <section className="join-routes" aria-labelledby="join-routes-heading"><div className="join-routes-heading"><p className="join-eyebrow">The contribution routes</p><h2 id="join-routes-heading">Pick a path.<br />We’ll meet you there.</h2></div><div className="join-route-list">{roles.map(({ number, title, icon: Icon, description, benefits, links }) => <article className="join-route" key={number}><div className="join-route-number">{number}</div><div className="join-route-icon"><Icon size={22} aria-hidden="true" /></div><div className="join-route-copy"><h3>{title}</h3><p>{description}</p><ul>{benefits.map(benefit => <li key={benefit}><Check size={14} aria-hidden="true" /> {benefit}</li>)}</ul></div><div className="join-route-links">{links.map(({ label, link }) => <a key={label} href={link} target="_blank" rel="noopener noreferrer">{label} <ArrowUpRight size={17} aria-hidden="true" /></a>)}</div></article>)}</div></section>
    <section className="join-closing"><div><p className="join-eyebrow">Not sure where to start?</p><h2>Start with your<br />curiosity.</h2></div><a href="mailto:flamivor@gmail.com">Ask the Flamivor team <ArrowUpRight size={18} aria-hidden="true" /></a></section>
  </main>
}
